
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://39.106.152.46:3306/bookstore?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root  
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: zstu.sjq.bean
  mapperLocations: classpath:mybatis/mapper/*.xml
