/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2018-01-13 13:47:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1502262948211L));
    _jspx_dependants.put("jar:file:/J:/FinalDesign/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookstore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>欢迎来到电子书城</title>\r\n");
      out.write("<!-- 获取app_path地址下面用到 -->\r\n");

	pageContext.setAttribute("APP_PATH",request.getContextPath());
 
      out.write("\r\n");
      out.write("<!-- 引入JQuery -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery.cookie.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquerySession.js\"></script>\r\n");
      out.write("<!-- 引入Boostrap -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <!--  -->\r\n");
      out.write("   <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/index.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 学校模态框 -->\r\n");
      out.write("\t\t<div class=\"modal fade school-modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("  \t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    \t\t\t<div class=\"modal-content\">\r\n");
      out.write("      \t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("        \t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        \t\t\t<h4 class=\"modal-title\">我的学校</h4>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("      \t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("        \t\t\t<h3>浙江理工大学，信息学院，14计算机科学与技术(1)，沈佳琦，2014329620023，毕业设计，</h3>\r\n");
      out.write("        \t\t\t<h3>导师:周志宇老师，题目:基于JAVA技术的图书电子商务系统实现</h3>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div><!-- /.modal-content -->\r\n");
      out.write("  \t\t\t</div><!-- /.modal-dialog -->\r\n");
      out.write("\t\t</div><!-- /.modal -->\r\n");
      out.write("\t<!-- 常见问题模态框 -->\r\n");
      out.write("\t\t<div class=\"modal fade question-modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("  \t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    \t\t\t<div class=\"modal-content\">\r\n");
      out.write("      \t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("        \t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        \t\t\t<h4 class=\"modal-title\">常见问题</h4>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("      \t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("        \t\t\t<h3>常见问题就是没有问题</h3>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t</div><!-- /.modal-content -->\r\n");
      out.write("  \t\t\t</div><!-- /.modal-dialog -->\r\n");
      out.write("\t\t</div><!-- /.modal -->\r\n");
      out.write("\t<!-- 搭建首页页面 -->\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<!-- 页面头:登陆,注册 -->\r\n");
      out.write("\t\t<div class=\"row\" id=\"head-top\">\r\n");
      out.write("\t\t\t<!-- 登陆前:注册登陆栏            登陆后:个人中心，购物车，注销 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\" id=\"head-mid\">\r\n");
      out.write("\t\t\t<!-- 导航栏 -->\r\n");
      out.write("\t\t\t<div class=\"col-md-2 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/logo.png\" width=\"165px\" height=\"50px\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-md-offset-3\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs nav-justified\">\r\n");
      out.write("  \t\t\t\t\t<li role=\"presentation\" class=\"active\" id=\"home\"><a href=\"#\">首页HOME</a></li>\r\n");
      out.write(" \t\t\t\t    <li role=\"presentation\"><a href=\"#\">开始选购！</a></li>\r\n");
      out.write("  \t\t\t\t\t<li role=\"presentation\"><a href=\"#\">联系我们</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\" >\r\n");
      out.write("\t\t\t<!-- 横幅 -->\r\n");
      out.write("\t\t\t<div class=\"jumbotron\" id=\"banner\">\r\n");
      out.write("  \t\t\t\t<h1>Hello, world!</h1>\r\n");
      out.write("  \t\t\t<p>欢迎来到电子图书商城，一个新世界！</p>\r\n");
      out.write("  \t\t\t<p><a class=\"btn btn-primary btn-lg\" href=\"#\" role=\"button\">了解更多</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"page-header col-md-offset-2\">\r\n");
      out.write("  \t\t\t<h1>热销书籍 <small>喜欢常来</small></h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\" id=\"shop\">\r\n");
      out.write("\t\t\t<!-- 商品展示 -->\r\n");
      out.write("  \t\t\t\t<div class=\"col-md-2 col-md-offset-2\">\r\n");
      out.write("    \t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("     \t\t\t\t\t <img src=\"...\" alt=\"...\">\r\n");
      out.write("      \t\t\t     <div class=\"caption\">\r\n");
      out.write("        \t\t\t\t<h3>Thumbnail label</h3>\r\n");
      out.write("        \t\t\t\t<p>...</p>\r\n");
      out.write("        \t\t\t\t<p><a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a href=\"#\" class=\"btn btn-default\" role=\"button\">Button</a></p>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 商品展示 -->\r\n");
      out.write("  \t\t\t\t<div class=\"col-md-2 col-md-offset-1\">\r\n");
      out.write("    \t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("     \t\t\t\t\t <img src=\"...\" alt=\"...\">\r\n");
      out.write("      \t\t\t     <div class=\"caption\">\r\n");
      out.write("        \t\t\t\t<h3>Thumbnail label</h3>\r\n");
      out.write("        \t\t\t\t<p>...</p>\r\n");
      out.write("        \t\t\t\t<p><a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a href=\"#\" class=\"btn btn-default\" role=\"button\">Button</a></p>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 商品展示 -->\r\n");
      out.write("  \t\t\t\t<div class=\"col-md-2 col-md-offset-1\">\r\n");
      out.write("    \t\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("     \t\t\t\t\t <img src=\"...\" alt=\"...\">\r\n");
      out.write("      \t\t\t     <div class=\"caption\">\r\n");
      out.write("        \t\t\t\t<h3>Thumbnail label</h3>\r\n");
      out.write("        \t\t\t\t<p>...</p>\r\n");
      out.write("        \t\t\t\t<p><a href=\"#\" class=\"btn btn-primary\" role=\"button\">Button</a> <a href=\"#\" class=\"btn btn-default\" role=\"button\">Button</a></p>\r\n");
      out.write("      \t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<h1>待开发区域</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"row\" id=\"footer\">\r\n");
      out.write("\t\t\t<!-- 底边 -->\r\n");
      out.write("\t\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t<h1>MORE INFO</h1>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-link\" \r\n");
      out.write("\t\t\t\tdata-toggle=\"modal\" data-target=\".school-modal\">学校</button>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-link\" \r\n");
      out.write("\t\t\t\tdata-toggle=\"modal\" data-target=\".question-modal\">常见问题</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- 联系方式 -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t<h1>CONTACT US</h1>\r\n");
      out.write("\t\t\t\t<p>如果你有更好的想法</p>\r\n");
      out.write("\t\t\t\t<p>更经典的创意</p>\r\n");
      out.write("\t\t\t\t<p>phone: +159 5800 31xx</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 col-md-offset-1\" id=\"logo-big\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/images/logo-big.png\" width=\"198px\" height=\"60px\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\" id=\"foot\">\r\n");
      out.write("\t\t\t\t<h3 class=\"text-center\">版权所有©沈佳琦</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t//跳转到商品浏览\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//判断登陆状态\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\tjudge_user_status();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction judge_user_status(){\r\n");
      out.write("\t\t\tif($.session.get('user')!=null){\r\n");
      out.write("\t\t\t\t//出现 欢迎个人用户和个人中心，购物车，注销\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar userString=$.session.get('user');\r\n");
      out.write("\t\t\t\tvar user=JSON.parse(userString)\r\n");
      out.write("\t\t\t\tvar userInfoBtn=$(\"<button></button>\").append(user.name).addClass('btn btn-link').attr(\"style\",\"color:#FFF\").attr('id','userInfo');\r\n");
      out.write("\t\t\t\tvar shopcatBtn=$(\"<button></button>\").append(\"购物车\").addClass('btn btn-link').attr(\"style\",\"color:#FFF\").attr('id','shopcat');\r\n");
      out.write("\t\t\t\tvar logoutBtn=$(\"<button></button>\").append(\"注销\").addClass('btn btn-link').attr(\"style\",\"color:#FFF\").attr('id','logout');\r\n");
      out.write("\t\t\t\tvar headLi=$(\"<div></div>\").addClass(\"col-md-3 col-md-offset-9\").\r\n");
      out.write("\t\t\t\tattr(\"id\",\"user_is_login\").append(\"欢迎您,\").append(userInfoBtn).append(shopcatBtn).append(logoutBtn);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#head-top').append(headLi);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#logout').click(function(){\r\n");
      out.write("\t\t\t\t\t$.session.remove('user');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\twindow.location.href=\"/bookstore\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//之后userInfo跳转到个人中心\r\n");
      out.write("\t\t\t\t$('#userInfo').click(function(){\r\n");
      out.write("\t\t\t\t\twindow.location.href=\"userInfo\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t//出现注册登录跳转页\r\n");
      out.write("\t\t\t\tvar registerBtn=$(\"<button></button>\").append(\"注册\").attr('id','register').addClass('btn btn-link').attr(\"style\",\"color:#FFF\");\r\n");
      out.write("\t\t\t\tvar loginBtn=$(\"<button></button>\").append(\"登录\").attr('id','login').addClass('btn btn-link').attr(\"style\",\"color:#FFF\");\r\n");
      out.write("\t\t\t\tvar headLi=$(\"<div></div>\").addClass(\"col-md-2 col-md-offset-10\").\r\n");
      out.write("\t\t\t\tattr(\"id\",\"user_not_login\").append(registerBtn).append(loginBtn);\r\n");
      out.write("\t\t\t\t$('#head-top').append(headLi);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//跳转到注册界面\r\n");
      out.write("\t\t\t\t$('#register').click(\r\n");
      out.write("\t\t\t\t\tfunction(){\r\n");
      out.write("\t\t\t\t\t\twindow.location.href=\"register\";\r\n");
      out.write("\t\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//跳转到注册界面\r\n");
      out.write("\t\t\t\t$('#login').click(\r\n");
      out.write("\t\t\t\t\tfunction(){\r\n");
      out.write("\t\t\t\t\t\twindow.location.href=\"login\";\r\n");
      out.write("\t\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
